name: "Upstream Sync"

on:
  schedule:
    - cron: "0 0 * * *" # 每天同步一次
    workflow_dispatch: 

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: Ac-Wiki/AcWiKi
          upstream_sync_branch: main
          target_sync_repo: Ac-Wiki/AcWiKi
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false